version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: dockerfile.stage
    ports:
      - "80:80"
    env_file:
      - "./.env.stage"
    environment:
      - REACT_APP_NAME=Rishabh stage
