version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - "80:80"
    env_file:
      - "./.env.production"
    environment:
      - REACT_APP_NAME=sanjeev
      - REACT_APP_URL=hello
