FROM node as build

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV REACT_APP_NAME='Rishabh bhai kya haal hai'
EXPOSE 3000
RUN npm run build


FROM nginx
COPY --from=build /app/build /usr/share/nginx/html

